services:
  weaviate-server:
    image: cr.weaviate.io/semitechnologies/weaviate:1.37.7
    healthcheck:
      test: wget --no-verbose --tries=3 --spider http://localhost:8081/v1/.well-known/ready || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - ./vector-db:/vector-db
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8081"
      - --scheme
      - http
    ports:
      - 8081:8081
      - 50051:50051
    restart: on-failure

  llama-server:
    image: ghcr.io/ggml-org/llama.cpp:server
    #platform: linux/arm64 # Specify arm64 for mac
    ports:
      - 8080:8080
    volumes:
      - ./models:/models
      - ./models.ini:/models.ini
    command:
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8080"
      - "--models-preset"
      - "/models.ini"
      - "--models-dir" # Enables multiple models on one server
      - "/models"
      - "--models-autoload"
      - "--models-max"
      - "1"
      - "--metrics"
      - "--verbose"
    depends_on:
      weaviate-server:
        condition: service_healthy

  chat-interface:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8082:8082"
    depends_on:
      llama-server:
        condition: service_started
      weaviate-server:
        condition: service_healthy

volumes:
  vector-db:
