---
services:
  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.37.0
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - weaviate_data:/vector-db/weaviate-data
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/vector-db"
      ENABLE_MODULES: "generative-ollama,text2vec-ollama"
      CLUSTER_HOSTNAME: "node1"

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - ollama_data:/root/.ollama

volumes:
  weaviate_data:
  ollama_data:
