services:
  llama-server:
    image: ghcr.io/ggml-org/llama.cpp:server
    platform: linux/arm64 # Specify arm64 for mac
    ports:
      - 8080:8080
    volumes:
      - ./models:/models
    command:
      - "--host"
      - "0.0.0.0"
      - "--port"
      - "8080"
      - "--models-dir" # Enables multiple models on one server
      - "/models"
      - "--models-autoload"
      - "--models-max"
      #- "--embeddings" Causes errors. Need a separate server for embedding model
      - "1"
      - "-c"
      - "2048"
      - "--n-cpu-moe" # Offloads model processing to CPU
      - "12"
      - "--verbose"

  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.37.7
    volumes:
      - ./vector-db:/vector-db
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8081"
      - --scheme
      - http
    ports:
      - 8081:8081
      - 50051:50051
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 8
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/vector-db" # Must match the value after `:` in `volumes` above
      ENABLE_MODULES: "text2vec-openai,generative-openai"
      OPENAI_APIKEY: "not-needed"
      OPENAI_BASEURL: "http://llama-server:8080/"
      CLUSTER_HOSTNAME: "node1" # Can be set to any name
      LOG_LEVEL: "debug"

volumes:
  vector-db:
