[*]
; Use all GPU layers
n-gpu-layers = 99
; Context length
c = 2048
; Batch size equal to context len
batch-size = 2048
ubatch-size = 1024
; Flash attention
fa = 1

;mlock - Might use later (also might cause excessive memory usage)

[Qwen3-8B-Instruct]
model = /models/Qwen3-8B-Q5_K_M.gguf
chat-template-kwargs = {"enable_thinking": false}

[Qwen3-8B-Instruct-Embed]
model = /models/Qwen3-8B-Q5_K_M.gguf
embedding = true
pooling = mean
