[*]
; Use all GPU layers
n-gpu-layers = 99
; Context length
c = 2048
; Batch size equal to context len
batch-size = 2048
ubatch-size = 1024
; Flash attention
fa = 1

;mlock - Might use later (also might cause excessive memory usage)

[Qwen2.5-7B-Instruct-Q4_K_M]
model = /models/Qwen2.5-7B-Instruct-Q4_K_M.gguf

[Qwen3-Embedding-8B-Q5_K_M]
model = /models/Qwen3-Embedding-8B-Q5_K_M.gguf
embedding = true
pooling = mean
