# %% Imports
import asyncio
from ddgs import DDGS
from crawl4ai import AsyncWebCrawler, CrawlerRunConfig
from crawl4ai.markdown_generation_strategy import DefaultMarkdownGenerator

# %% DuckDuckGo Search Tool
# Find out if there's a chunk splitter designed for crawl4ai results
# Also... there's probably a better way to do this function in Go
def duckduckgo_search(search_query: str, max_results: int) -> list:
    result = DDGS().text(search_query, max_results=max_results)

    # Extract only the hrefs (urls) from the `result` dictionary
    hrefs = [r["href"] for r in result]

    return hrefs

# %% Test Search
max_results = 8
test_search = duckduckgo_search("benefits and drawbacks of llama.cpp library", max_results)
print(test_search)

# %% Crawler
# THIS WAS GENERATED BY AI AND REQUIRES REVIEW!!!
# But... it seems like it's working as of now
# I really gotta figure out async...
async def crawl_urls(urls: list[str]) -> list[dict]:
    config = CrawlerRunConfig(
        markdown_generator=DefaultMarkdownGenerator()
    )

    async with AsyncWebCrawler() as crawler:
        results = await crawler.arun_many(urls, config=config)

    output = []
    for result in results:
        if result.success:
            output.append({
                "url": result.url,
                "markdown": result.markdown
            })
        else:
            print(f"Failed: {result.url} — {result.error_message}")

    return output


async def search_and_crawl(query: str, max_results: int = 8) -> list[dict]:
    urls = duckduckgo_search(query, max_results)
    print(f"Found {len(urls)} URLs, crawling...")
    return await crawl_urls(urls)

if __name__ == "__main__":
    results = asyncio.run(search_and_crawl("benefits and drawbacks of llama.cpp library"))

    for r in results:
        print(f"\n--- {r['url']} ---")
        print(r["markdown"][:500])  # Preview first 500 chars
